AWSTemplateFormatVersion: "2010-09-09"
Description: >
  VPC Architecture Scenario - Hands-on for portfolio.
  Creates VPC, subnets, IGW for testing routing and network setup.

Parameters:
  VPCName:
    Type: String
    Default: TestVPC
    Description: "Name of VPC"

Resources:
  TestVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Ref VPCName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TestVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref TestVPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VPCID:
    Description: "VPC ID"
    Value: !Ref TestVPC

  PublicSubnetID:
    Description: "Public Subnet ID"
    Value: !Ref PublicSubnet
