AWSTemplateFormatVersion: "2010-09-09"
Description: >
  EC2 Troubleshooting Scenario - Hands-on for my AWS portfolio.
  Spins up an EC2 instance and Security Group to practice real-world connectivity issues.

Parameters:
  DefaultVPC:
    Type: AWS::EC2::VPC::Id
    Description: "The VPC ID where the instance will go"

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Your EC2 KeyPair for SSH access"

Resources:
  # Security Group
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for EC2 troubleshooting"
      VpcId: !Ref DefaultVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0   # Only SSH for testing
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: EC2-Troubleshoot-Portfolio

Outputs:
  EC2PublicIP:
    Description: "Public IP for SSH testing"
    Value: !GetAtt EC2Instance.PublicIp

  SecurityGroupID:
    Description: "Security Group ID"
    Value: !Ref EC2SecurityGroup
